### ISSUE TITLE
Change the namespace

### ISSUE THREAD

**Issue by ismaail** [sarfraznawaz2005/visitlog#1]
Thanks a lot for the package,

please consider changing the namespace to something simpler like `Sarfraz` or `SarfrazNawaz`

**Comment by sarfraznawaz2005** [comment]
Thanks for liking the package.

Any particular reason for change of namespace ?

Actually this is my official username on github and elsewhere that's why I have used it. Secondly, there can be many other `Sarfraz` and `SarfrazNawaz` with possibility of similar package names now or in future so this unique namespace also saves me from that :)
